services:
  - type: web
    name: naye-valorant-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_KEY
        sync: false
      - key: PORT
        value: "10000"
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
      - key: TWITCH_CHANNEL_LOGIN
        sync: false
      - key: TWITCH_USER_TOKEN
        sync: false
      - key: TWITCH_ENDPOINT_PASSWORD
        sync: false
    healthCheckPath: /healthz
    plan: free
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
