services:
  - type: web
    name: naye-valorant-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_KEY
        sync: false
      - key: PORT
        value: "10000"
    healthCheckPath: /
    plan: free
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1